name=Artnet C
version=0.0.1
author=Samuel Hafen
maintainer=Samuel Hafen <samuel.hafem@ikmail.com>
sentence=Pure C library for the ArtNet protocol.
paragraph=Implements a Parser for ArtNet.
category=Communication
url=https://github.com/Soraxem/artnet-c
architectures=*
includes= #no abstraction given jet